"""add_pitch_type_to_boards

Revision ID: 29df27b645a2
Revises: 85992c15c122
Create Date: 2026-04-20 07:56:14.098888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29df27b645a2'
down_revision: Union[str, Sequence[str], None] = '85992c15c122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('pitch_type', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'pitch_type')
    # ### end Alembic commands ###
