"""add_versioning_columns

Revision ID: e09be5a56584
Revises: 29df27b645a2
Create Date: 2026-05-15 08:34:25.783177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e09be5a56584'
down_revision: Union[str, Sequence[str], None] = '29df27b645a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column('boards', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('frames', sa.Column('version', sa.Integer(), nullable=True))
    
    # Update existing rows
    op.execute("UPDATE boards SET version = 1")
    op.execute("UPDATE frames SET version = 1")
    
    # Set to NOT NULL
    op.alter_column('boards', 'version', nullable=False)
    op.alter_column('frames', 'version', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('frames', 'version')
    op.drop_column('boards', 'version')
    # ### end Alembic commands ###
